### PR TITLE
added a translation in swahili

### PR DESCRIPTION
**Pull request by the1Riddle**
# Swahili translation
added a Swahili translation on code of conduct file.

### CODE REVIEW

**Comment by the1Riddle** [comment]
hello, @CoralineAda, please check out my PR
Address #1363

**Review by rezzcode — COMMENTED** [review]
the language name and language code are added as required.

**Review by Peter-Mwangi254 — COMMENTED** [review]
I've thoroughly reviewed the translated version of the Code of Conduct, and I'm impressed with the quality and attention to detail in the translation. The Swahili translation maintains the essence and clarity of the original document, ensuring that it effectively conveys the ethical guidelines for community participation.

**Review by devharnold — COMMENTED** [review]
Translation of this was added to swahili.

**Review by CoralineAda — APPROVED** [review]
Thank you so much for bringing Contributor Covenant to Swahili!

**Pull request merged**
