### PR TITLE
Add Open Privacy Tech

### PR DESCRIPTION
**Pull request by souravcipher**
Added Open Privacy Tech to the adopters list.

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi @souravcipher , can you please provide a link to where the code of conduct is? I couldn't find it in any of your org's repositories. Thanks!

**Comment by souravcipher** [comment]
Hi @CoralineAda, here are the links
https://github.com/openprivacytech/.github/blob/main/CODE_OF_CONDUCT.md
https://www.openprivacytech.org/code-of-conduct

**Comment by CoralineAda** [comment]
Great, thanks!

**Review by CoralineAda — APPROVED** [review]

**Comment by Azizkhan1122** [comment]
Whts is this

**Pull request merged**
