### PR TITLE
Add initial Swedish translation of v2.1

### PR DESCRIPTION
**Pull request by janderssonse**
The latest Swedish translation was 1.4. This is an 2.1 retranslation, trying to use terms common in the Swedish Open Source world. with terms like erkännande=attribution, uppförandekod=code of conduct, gemenskap=community etc.

It it most likely not perfect, but ok  ,I threw it out for review on LinkedIn also - https://www.linkedin.com/posts/josefandersson_contributor-covenant-activity-6995726643499544576-doem?utm_source=share&utm_medium=member_desktop -, where there are quite a few people in the Swedish Open Source Community. So I'll hopefully I'll get some further feedback if there is anything important to fix. And.. I also intend to update the Swedish translation in the future, if I get suggestions or discover something odd.

Signed-off-by: Josef Andersson <josef.andersson@gmail.com>

### CODE REVIEW

**Comment by mattiasaxell** [comment]
This would be awesome to have merged! Great PR @janderssonse!

**Comment by janderssonse** [comment]
> This would be awesome to have merged! Great PR @janderssonse!

Hope it will, be, Thanks, and if you have any improvement suggestions, just add or correct.

**Comment by janderssonse** [comment]
@CoralineAda I just wanted to highlight that this translation was proofread by native Swedish speaker and colleague in https://github.com/EthicalSource/contributor_covenant/pull/1143/commits/0c31b2981dc332793e14214772d764888cb14c02 so hoping to see it getting further.

**Comment by mattiasaxell** [comment]
@janderssonse I've also proofread now (native speaker) and the fix looks great. Would love to see a merge @CoralineAda so I can start using it officially in projects. :smile:

**Review by CoralineAda — APPROVED** [review]
Thank you!

**Pull request merged**
