### PR TITLE
Add Maximilian to adopters.csv

### PR DESCRIPTION
**Pull request by meikalei**
Thanks for this! ✨

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in that repo?

**Comment by meikalei** [comment]
@CoralineAda Hi! it's still on a pull request but it was approved to be added already :)

**Comment by CoralineAda** [comment]
Let me know when it’s there?

**Comment by meikalei** [comment]
Hi! @CoralineAda it's there now :)

**Comment by meikalei** [comment]
Hi! It's there now :)

**Comment by CoralineAda** [comment]
Thanks!

**Pull request merged**
