### PR TITLE
add explanatory text stating that this is not an exhaustive list of cause

### PR DESCRIPTION
**Pull request by dariaphoebe**

### CODE REVIEW

**Comment by ryanoasis** [comment]
Seems like a good idea/change :+1:

**Comment by mikemorris** [comment]
:+1:

**Comment by webmaven** [comment]
:+1:

**Comment by ceaess** [comment]
Maybe I'm missing something, but doesn't "examples" connote non-exhaustivity?

**Comment by RichardLitt** [comment]
@ceaess is right, but adding this is smart because redundancy in language is sometimes smart. 

@dariaphoebe Needs a rebase.

**Comment by mcantelon** [comment]
+1

**Comment by webmaven** [comment]
@dariaphoebe, can you rebase this PR?

**Pull request closed without merging**
