### PR TITLE
align 1.3.0 french translation on original

### PR DESCRIPTION
**Pull request by jmettraux**
Meilleures salutations.

### CODE REVIEW

**Comment by CoralineAda** [comment]
@brunogirin brunogirin would you mind weighing in on the proposed changes?

**Comment by jmettraux** [comment]
@abelards if you could have a look at it too. Merci d'avance.

**Comment by abelards** [comment]
Fine with me, thanks for the fixes! :+1:

**Comment by brunogirin** [comment]
@CoralineAda sorry for coming back late, the changes are sensible so happy with them.

**Pull request merged**
