### PR TITLE
Also list class.

### PR DESCRIPTION
**Pull request by postmodern**
Also list (economic) class, along with age, race, ethnicity, etc. By not listing class we give the impression that class and classism does not exist, or that we all belong to the same class. Both of which are false.

### CODE REVIEW

**Comment by webmaven** [comment]
:+1:

**Comment by ceaess** [comment]
@CoralineAda, perhaps we should create an issue / have a larger discussion to develop a policy around additions to this list?

**Comment by webmaven** [comment]
@ceaess:
> perhaps we should create an issue / have a larger discussion to develop a policy around additions to this list?

:+1:

**Comment by RichardLitt** [comment]
I'm not sure that this PR warrants a larger discussion, before being merged. It states a good point, and is a good addition. An issue about subsequent additions would be good, though.

LGTM.

**Comment by mcantelon** [comment]
Class has been a vector of marginalization throughout human history.

+1

**Comment by webmaven** [comment]
So, can this be merged?

**Comment by sigmavirus24** [comment]
@webmaven it appears it *can* be, but I don't think there's consensus on whether it *should* be.

**Comment by webmaven** [comment]
Is there a mechanism or process to make a request for comments in order to check for consensus?

**Comment by CoralineAda** [comment]
I'm open to adding class to the next version. Labeled appropriately.

**Comment by webmaven** [comment]
Does that mean it is in, or does there still need to some sort of vote, poll, or referendum?

**Comment by CoralineAda** [comment]
It’s ultimately my decision but I appreciate and consider input from others.

**Comment by webmaven** [comment]
I vote 👍.

**Review by hosseinradmand — COMMENTED** [review]
Hack telegram

**Comment by webmaven** [comment]
@hosseinradmand, what does that mean?

**Pull request closed without merging**
