### PR TITLE
Update adopters.csv

### PR DESCRIPTION
**Pull request by danias**
Added Bitloops to the adopters.csv in the right order

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi @danias , I couldn't find a CODE_OF_CONDUCT.md or similar in the repositories-- can you please share where it lives?

**Comment by danias** [comment]
Hi @CoralineAda the main repo we are close to opening to the public that has it is closed for the next few days but I added it in a couple more: 

https://github.com/bitloops/bitloops-gherkin-ts/blob/main/CODE_OF_CONDUCT.md
https://github.com/bitloops/bitloops-language/blob/main/CODE_OF_CONDUCT.md

Thanks!

**Comment by CoralineAda** [comment]
Your code of conduct says to report issues to `conduct@ethicalsource.dev`. Please replace this with the contact method for _your org_-- we are not responsible for enforcement! :)

**Comment by danias** [comment]
Sorry about that :) Done!

**Comment by CoralineAda** [comment]
Ha, no problem!

**Review by CoralineAda — APPROVED** [review]

**Pull request merged**
