### PR TITLE
Add Mailspring to Adopters

### PR DESCRIPTION
**Pull request by CodeMouse92**

### CODE REVIEW

**Comment by Ondra1230** [comment]
[]()

**Comment by CodeMouse92** [comment]
@Ondra1230 Sorry, did you mean to leave a comment? I can't see anything.

**Comment by Ondra1230** [comment]
It is not possible  sur 18/01/2021 le 08:51, Jason C. McDonald écrivit:
                
            
            
                
                    De: "Jason C. McDonald" <notifications@github.com>Date: 18 janvier 2021à: "ContributorCovenant/contributor_covenant" <contributor_covenant@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"Ondra1230" <Ondra123@mail.com>Objet: Re: [ContributorCovenant/contributor_covenant] Add Mailspring to Adopters (#899)
                
                
@Ondra1230 Sorry, did you mean to leave a comment? I can't see anything.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762297863",
"url": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762297863",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CodeMouse92** [comment]
What is not possible?

**Review by CoralineAda — APPROVED** [review]

**Comment by CoralineAda** [comment]
@CodeMouse92 that was spam, sorry. Blocked that user. Thanks for the PR— merging now!

**Comment by CodeMouse92** [comment]
Woo hoo! Thanks, @CoralineAda!

**Comment by Ondra1230** [comment]
I don’t know maybe GFX is best all type.. sur 18/01/2021 le 12:34, Jason C. McDonald écrivit:
                
            
            
                
                    De: "Jason C. McDonald" <notifications@github.com>Date: 18 janvier 2021à: "ContributorCovenant/contributor_covenant" <contributor_covenant@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"Ondra1230" <Ondra123@mail.com>Objet: Re: [ContributorCovenant/contributor_covenant] Add Mailspring to Adopters (#899)
                
                
What is not possible?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762412370",
"url": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762412370",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ondra1230** [comment]
Only for trying? 😄  sur 18/01/2021 le 13:11, Jason C. McDonald écrivit:
                
            
            
                
                    De: "Jason C. McDonald" <notifications@github.com>Date: 18 janvier 2021à: "ContributorCovenant/contributor_covenant" <contributor_covenant@noreply.github.com>Cc: "Ondra1230" <Ondra123@mail.com>,"Mention" <mention@noreply.github.com>Objet: Re: [ContributorCovenant/contributor_covenant] Add Mailspring to Adopters (#899)
                
                
Woo hoo! Thanks, @CoralineAda!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762427023",
"url": "https://github.com/ContributorCovenant/contributor_covenant/pull/899#issuecomment-762427023",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
