### PR TITLE
Adding Hugo to adopters.csv

### PR DESCRIPTION
**Pull request by vidhyav656**
Added Hugo: [Hugo Official Website](https://gohugo.io/) and [Repo link](https://github.com/gohugoio/hugo)

### CODE REVIEW

**Comment by CoralineAda** [comment]
This adoption makes me very happy— I use Hugo on all my static sites. I don't see a CODE_OF_CONDUCT.md file in the repo though, and I didn't see any mention of the CoC on the Contributing doc site. Where can someone find it?

**Comment by vidhyav656** [comment]
> This adoption makes me very happy— I use Hugo on all my static sites. I don't see a CODE_OF_CONDUCT.md file in the repo though, and I didn't see any mention of the CoC on the Contributing doc site. Where can someone find it?

I love working with Hugo site. Contributing to this repo is my pleasure. Thank you for the opportunity. 

I am not following on the other question of CODE_OF_CONDUCT.md. I didn't understand it through.

**Comment by CoralineAda** [comment]
I'm asking where the code of conduct for Hugo is displayed? I can't find it on either GitHub or the doc site. Can you provide a URL?

**Comment by vidhyav656** [comment]
This is irrelevant for this repo. Sorry, to bother you. Thank you for your time through.

**Pull request closed without merging**
