### PR TITLE
Add PatternFly to the adopter list.

### PR DESCRIPTION
**Pull request by mindreeper2420**
I'd like to add PatternFly to the adopter list. Our Contribution Guidelines following the Contributor Covenant guidelines.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I can’t find the code of conduct in your project at all. Are you open to adding a CODE_OF_CONDUCT.md file to the repo or linking to it in the README? If I can’t find it and I know it’s there, I imagine that people who don’t know it’s there will assume that it doesn’t exist.

**Comment by mindreeper2420** [comment]
We can add the CODE_OF_CONDUCT.md file to our repo.  I've put a PR into the PatternFly repo.

**Comment by mindreeper2420** [comment]
The PR has been approved and there is now a CODE_OF_CONDUCT.md file in the repo.

**Comment by CoralineAda** [comment]
The email address for reporting violations has to be one associated with the project. covenant@idolhands.com is one of my email addresses and is not appropriate as I am not responsible for enforcing your code of conduct.

**Comment by mindreeper2420** [comment]
The file has been updated in the repo to reflect the proper contact email.

**Comment by CoralineAda** [comment]
Thanks!

**Pull request merged**
