### PR TITLE
Add PyMC3 to list of adopters

### PR DESCRIPTION
**Pull request by eigenfoo**
PyMC3's code of conduct can be found [here](https://github.com/pymc-devs/pymc3/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by CoralineAda** [comment]
Did you mean to use 1.2 instead of 1.4?

**Comment by eigenfoo** [comment]
Ah, I didn't know we've moved on to v1.4. I'll loop back with the rest of the PyMC3 development team. Thank you!

**Comment by eigenfoo** [comment]
@CoralineAda just to loop back, we've bumped up out CoC to 1.4! Thank you so much!

https://github.com/pymc-devs/pymc3/pull/3200

**Comment by CoralineAda** [comment]
Nice, thanks!

**Pull request merged**
