### PR TITLE
Add ArchiSteamFarm to adopters.csv

### PR DESCRIPTION
**Pull request by JustArchi**
https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/.github/CODE_OF_CONDUCT.md

Thank you in advance for considering this PR.

### CODE REVIEW

**Review by CoralineAda — APPROVED** [review]

**Comment by CoralineAda** [comment]
Thanks!

**Review by Muradalsaaideh — APPROVED** [review]

**Review by Hyran15 — COMMENTED** [review]
static/adopters.csv

**Review by tuxtvixx — COMMENTED** [review]
Easy steps.. Even if you you attend to make it for the very first time..

**Comment by ratchanonsuttawas** [comment]
> https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/.github/CODE_OF_CONDUCT.md
> 
> Thank you in advance for considering this PR.

**Review by Amirshariati — COMMENTED** [review]
Ok

**Review by Amirshariati — COMMENTED** [review]
Ok

**Review by oszvalddavid — COMMENTED** [review]
<a name="languages">Additional languages available</a>: [Bahasa Indonesia](//creativecommons.org/licenses/by/4.0/legalcode.id), [Nederlands](//creativecommons.org/licenses/by/4.0/legalcode.nl), [norsk](//creativecommons.org/licenses/by/4.0/legalcode.no), [suomeksi](//creativecommons.org/licenses/by/4.0/legalcode.fi), [te reo Māori](//creativecommons.org/licenses/by/4.0/legalcode.mi), [українська](//creativecommons.org/licenses/by/4.0/legalcode.uk), [日本語](//creativecommons.org/licenses/by/4.0/legalcode.ja). Please read the [FAQ](//wiki.creativecommons.org/FAQ#officialtranslations) for more information about official translations.

**Review by xztmhs4-spec — COMMENTED** [review]
Nice

**Review by hunningstack — COMMENTED** [review]
actually

**Review by 0xsarawut-eth — COMMENTED** [review]
https://github.com/EthicalSource/contributor_covenant/releases/tag/2.1

**Pull request merged**
