### PR TITLE
Adding City of Sault Ste. Marie to adopters.csv

### PR DESCRIPTION
**Pull request by dangowans**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi! I couldn't find the code of conduct in any of your repos-- can you please point me to the right place?

**Comment by dangowans** [comment]
Here's a few.  Thank you for your consideration.

https://github.com/cityssm/general-licence-manager/blob/main/CODE_OF_CONDUCT.md
https://github.com/cityssm/lot-occupancy-system/blob/main/CODE_OF_CONDUCT.md
https://github.com/cityssm/lottery-licence-manager/blob/master/CODE_OF_CONDUCT.md
https://github.com/cityssm/parking-ticket-system/blob/master/CODE_OF_CONDUCT.md

**Comment by CoralineAda** [comment]
Great, thank you!

**Review by CoralineAda — APPROVED** [review]

**Comment by dangowans** [comment]
Thank you!  : )

**Pull request merged**
