### PR TITLE
add Skeet to adopeters csv

### PR DESCRIPTION
**Pull request by POPPIN-FUMI**
# Contributor Covenant Adoption

## Project name
Skeet

## Project repository
https://github.com/elsoul/skeet

## Link to code of conduct in your project's repo or documentation
[Code of conduct](https://github.com/elsoul/skeet/blob/main/CODE_OF_CONDUCT.md)

Thank you!

### CODE REVIEW

**Review by CoralineAda — APPROVED** [review]
Thanks!

**Review by Eryk1705 — COMMENTED** [review]
#1205

**Comment by Masoudahgl** [comment]
> # Contributor Covenant Adoption
> ## Project name
> Skeet
> 
> ## Project repository
> https://github.com/elsoul/skeet
> 
> ## Link to code of conduct in your project's repo or documentation
> [Code of conduct](https://github.com/elsoul/skeet/blob/main/CODE_OF_CONDUCT.md)
> 
> Thank you!

You're welcome

**Review by Masoudahgl — COMMENTED** [review]
Like

**Review by Masoudahgl — COMMENTED** [review]
Like

**Pull request merged**
