### PR TITLE
add arabic translation

### PR DESCRIPTION
**Pull request by melbahja**
arabic translation added

### CODE REVIEW

**Comment by CoralineAda** [comment]
This looks great, thank you SO much! I will start looking for another native speaker to review the translation.

**Comment by melbahja** [comment]
@CoralineAda thanks to you :smile:  my friends @SaidElBakkali form wordpress arabic translation community and @lotfio also is a native arabic speaker

**Comment by bmak91** [comment]
There are some minor translation and grammatical errors, but I'm not sure how to go about suggesting edits.

**Comment by melbahja** [comment]
@bmak91 give me your suggestions

**Comment by bmak91** [comment]
@melbahja I added the text with my edits below, hopefully this is the place and I didn't mess up the formatting

Edit: I should have also mentioned that it was a great initial work you did.

```
+++
version = "1.4"
aliases = ["/version/1/4"]
+++

<div dir="auto">

# ميثاق القواعد السلوكية للمساهمين

## تَعهُدنا

من أجل تعزيز بيئة مفتوحة وترحيبية، نحن المساهمون والمشرفون نتعهد بجعل المشاركة في مشروعنا ومجتمعنا تجربة خالية من المضايقات للجميع، بغض النظر عن العمر، أو الجسد ، أو العجز، أو العرق، أو الخصائص الجنسية، أو الهوية الجندرية  وطريقة التعبير عنها، أو مستوى الخبرة والتعليم، أو الوضع الاجتماعي والاقتصادي، أو الجنسية، أو المظهر، أو العرق، أو الدين، أو الهوية والتوجه الجنسيين.

## معاييرنا

أمثلة على السلوك الذي يساهم في خلق بيئة إيجابية تتضمن:

* إستخدام لغة ترحيبية وشاملة
* احترام وجهات النظر والخبرات المختلفة
* قبول النقد البناء بلطف
* التركيز على ما هو أفضل للمجتمع
* إظهار التعاطف تجاه أعضاء المجتمع الآخرين

أمثلة على السلوك غير المقبول من قبل المشاركين تشمل:

* استخدام لغة أو صور جنسية والاهتمام الجنسي غير المرغوب فيه أو التحرش
* التصيد، والتعليقات المهينة/الازدرائية، والهجمات الشخصية أو السياسية 
* مضايقات عامة أو خاصة
* نشر المعلومات الخاصة للآخرين، مثل المعلومات المادية أو الإلكترونية دون إذن صريح
* التصرفات الأخرى التي يمكن اعتبارها غير مناسبة في الإطار المهني

## مسؤولياتنا

مشرفو المشروع مسؤولون عن توضيح معايير السلوك المقبول ومن المتوقع اِتخاذ إجراءات تصحيحية مناسبة وعادلة في الاستجابة لأي حالات من السلوك المرفوض.

يمتلك مشرفو المشروع الحق والمسؤولية بإزالة أو تعديل أو رفض التعليقات، والإيداعات، والكود، وتعديلات الويكي، والمسائل، والمساهمات الأخرى التي لا تتماشى مع القواعد السلوكية هذه، أو حظر، مؤقتًا أو بصفة دائمة، أي مساهم بسلوكيات أخرى يرونها غير مناسبة، أو بمثابة تهديد أو هجوم أو إلحاق ضرر. 

## الإطار

تنطبق قواعد السلوك هذه على حد سواء داخل مساحات المشروع والمساحات العامة عندما يمثل الفرد المشروع أو مجتمعه. أمثلة على ذلك تشمل استخدام البريد الإلكتروني الرسمي للمشروع، أو النشر عبر الحساب الرسمي لوسائل التواصل الاجتماعي، أو التصرف كَممثل مُعَين في حدث عبر الإنترنت أو خارجه.  وللمشرفين تعريف وتوضيح معنى تمثيل المشروع بشكل أوسع.

## التنفيذ

يتم الإبلاغ عن حالات السلوك التعسفي، أو المضايقة أو السلوك غير المقبول بشكل عام عن طريق الاتصال بفريق المشروع على [إضافة العنوان البريدي]. ستتم مراجعة كل الشكاوى والتحقيق فيها وسوف ينتج عنها ردا يعتبر ضروريا ومناسبا للظروف. إن فريق المشروع ملزم بالحفاظ على سرية المبلغ عن الحادث. قد يتم نشر تفاصيل إضافية عن سياسات تنفيذية محددة بشكل منفصل.

إن مشرفي المشروع الذين لا يتبعون أو يطبقون القواعد السلوكية بنية حسنة قد يواجهون تداعيات مؤقتة أو دائمة على النحو الذي يحدده أعضاء قيادة المشروع الآخرين.

## الإسناد

يتم تكييف قواعد السلوك هذه من [Contributor Covenant][homepage], الإصدار 1.4,
متاح في <https://www.contributor-covenant.org/ar/version/1/4/code-of-conduct>

[homepage]: https://www.contributor-covenant.org
</div>

```

**Comment by melbahja** [comment]
@bmak91 that good thank you 
but i think we can replace 
" الهوية والتوجه الجنسيين" 
with 
"الهوية الجنسية والتوجه"
https://ar.wikipedia.org/wiki/%D9%87%D9%88%D9%8A%D8%A9_%D8%AC%D9%86%D8%B3%D9%8A%D8%A9

**Comment by bmak91** [comment]
@melbahja Yeah I wasn't too sure about that when I wrote it, I considered 
"الهوية الجنسية والتوجه"
and kept thinking what "توجه"? (i.e something feels missing) Maybe "جنسي" can be repeated, or simply we stick to "الهوية الجنسية".
We might also see what other people might suggest.

**Comment by melbahja** [comment]
@bmak91 i think  "الهوية الجنسية" good 
without "توجه"

**Comment by melbahja** [comment]
@CoralineAda i think the translation is ready now

**Comment by CoralineAda** [comment]
Great, thank you to everyone who helped too!

**Pull request merged**
