### PR TITLE
Add first contributions to adopters list

### PR DESCRIPTION
**Pull request by Roshanjossey**
Added a link to [First Contributions](https://github.com/multunus/first-contributions)

### CODE REVIEW

**Comment by CoralineAda** [comment]
Wonderful, thanks!

**Comment by Roshanjossey** [comment]
@CoralineAda: First contributions is aimed at helping beginners to get started with contributing to open source projects. I'd love it it you could take a look at the project and give me some feedback.

As a person who has a lot of experience in open source community, your feedback will be much useful for me

**Comment by CoralineAda** [comment]
https://twitter.com/CoralineAda/status/827251252849410049

**Comment by Roshanjossey** [comment]
@CoralineAda Wow this is awesome. Thank you very much. I am honoured

**Pull request merged**
