### PR TITLE
A few fixes for the French translation

### PR DESCRIPTION
**Pull request by lrz**

### CODE REVIEW

**Comment by CoralineAda** [comment]
I forgot to check this before merging. Can you please update the HTML and text versions as well?

**Comment by lrz** [comment]
Oh I'm sorry, I thought these were automatically generated. I will do that tomorrow!

**Comment by lrz** [comment]
I created a new pull request with the other changes: https://github.com/ContributorCovenant/contributor_covenant/pull/267

**Comment by benoittgt** [comment]
Thanks for it @lrz

**Pull request merged**
