### PR TITLE
Tamil Translation

### PR DESCRIPTION
**Pull request by SaravananOffl**

### CODE REVIEW

**Comment by SaravananOffl** [comment]
Is everything alright?!

**Comment by CoralineAda** [comment]
On Monday I'll tweet looking for another native Tamil speaker to review the translation. Every translation has to be reviewed before I make it public.

Thanks for all the hard work!

**Comment by SaravananOffl** [comment]
fixes #467

**Comment by Roshanjossey** [comment]
@CoralineAda, Do you need help to get reviewers for this? I could talk to some of my friends. I could help you out with most Indian languages as well

**Comment by CoralineAda** [comment]
Yes, if you could find some reviewers that would be great! Sorry it took so long to reply.

**Comment by Roshanjossey** [comment]
@CoralineAda, No worries. I'll reach out to some of my friends. I'd love to help you in maintaining this project. I'd love to have a conversation around that. You can find my mail address in my GitHub profile.

**Comment by Roshanjossey** [comment]
@antonyraji, Could you please do a review of this translation?

**Pull request closed without merging**
