### PR TITLE
Add Data Retriever

### PR DESCRIPTION
**Pull request by henrykironde**
Adding data retriever to list of projects that have adapted
the Contributor Covenant.

Disclaimer:
Contributor covenant reserves the right to disregard this Pull request if the content or use of the code does not meet the required use and rights.

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hey there, I can't find the code of conduct in your project. Where is it?

**Comment by henrykironde** [comment]
We have it in all these locations 
https://github.com/weecology/retriever/blob/master/docs/code_of_conduct.rst
http://retriever.readthedocs.io/en/latest/code_of_conduct.html
And we have listed it  as the last link in the home page
http://www.data-retriever.org/

**Comment by CoralineAda** [comment]
Just a note… it's best placed at the root level of your project as CODE_OF_CONDUCT.md

Thanks!

**Comment by henrykironde** [comment]
Thank you @CoralineAda

**Pull request merged**
