### PR TITLE
Add `friends` to adopters list

### PR DESCRIPTION
**Pull request by JacobEvelyn**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi Jacob! You need to replace `[INSERT EMAIL ADDRESS]` under the Enforcement section with your actual email address. Let me know when you've done that and I will merge the PR,

**Comment by JacobEvelyn** [comment]
Whoops! Sorry for missing that. I've added my email address. Thanks!

**Comment by CoralineAda** [comment]
Thanks Jacob!

**Comment by JacobEvelyn** [comment]
Thanks so much!

**Pull request merged**
