### PR TITLE
add kornia project to adopters

### PR DESCRIPTION
**Pull request by edgarriba**
As Kornia project maintainer I would like to add our link in here.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in your repo?

**Comment by edgarriba** [comment]
hi @CoralineAda thanks for reviewing. Just merged, check it out:
https://github.com/arraiyopensource/kornia/blob/master/CODE_OF_CONDUCT.md

**Comment by CoralineAda** [comment]
Thanks!

**Comment by edgarriba** [comment]
:D

**Pull request merged**
