### PR TITLE
Ask for tolerance, not respect

### LINKED ISSUE #892: It's reasonable to expect tolerance, not respect
The current version states the following as expected behavior:

* Being **respectful** of differing opinions, viewpoints, and experiences

However, as the recent debate regarding Cambridge University's freedom of speech policy demonstrates; respect cannot be mandated: [Cambridge University rejects proposal it be 'respectful' of all views](https://www.theguardian.com/world/2020/dec/09/cambridge-university-rejects-proposal-it-be-respectful-of-all-views).

Respect cannot be manufactured at will. If you don't respect an idea (for example that the Earth is flat), then it doesn't matter how hard you try; you still will not respect it. In that sense respect is like belief; nobody can force you to believe the Moon is made of cheese. Either you do or you don't.

You can pretend to believe in something, and you can pretend to respect something, but you really don't. Any policy that asks people to pretend is not a good policy.

As Stephen Fry puts it:

> A demand for respect is like a demand for a laugh, or demands for love, loyalty and allegiance. They cannot be given if not felt.

The commitment should be towards tolerance; which can be honestly given, not respect; which can only be faked.

Additionally, the purpose of the contributor covenant is to be enforced, not merely added as a dead document. Currently many projects do not enforce respect, in fact, differing opinions are constantly disrespected and dismissed.

Instead of demanding something that no project enforces, and cannot enforce, the covenant should request tolerance, which is what 86.9% of the governing body of Cambridge University ultimately decided was the sensible thing to do, after scrutiny from countless intellectuals, and the society in general, not only from the United Kingdom, but the world.

* Being **tolerant** of differing opinions, viewpoints, and experiences

That means even if you don't personally respect an opinion (hold it in high regard), you should still tolerate it (allow it to exist).

### PR DESCRIPTION
**Pull request by felipec**
Respect cannot be manufactured at will. If you don't respect an idea
(for example that the Earth is flat), then it doesn't matter how hard
you try; you still will not respect it. In that sense respect is like
belief; nobody can force you to believe the Moon is made of cheese.
Either you do or you don't.

You can pretend to believe in something, and you can pretend to respect
something, but you really don't. Any policy that asks people to pretend
is not a good policy.

The commitment should be towards tolerance; which can be honestly given,
not respect; which can only be faked.

A nuanced debate over tolerance versus respect can be seen in the
proposal at Cambridge University to demand respect. Tolerance won.

Fixes #892.

Signed-off-by: Felipe Contreras <felipe.contreras@gmail.com>

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi Felipe, first of all thank you for this. 

I understand the point you're making, but in my own experience with marginalization, there is a huge difference between being "tolerated" and having my identity (and even my fundamental human rights)  _respected_.

The word "respect" in this context does not mean that same thing as the sort of respect that you engender in other people by your words and actions, the kind of respect you earn. Rather, it means respect for someone else's validity and humanity. For example, as a transgender woman, I don't want my identity to be simply "tolerated". 

This is a very important distinction.

**Comment by felipec** [comment]
> I understand the point you're making, but in my own experience with marginalization, there is a huge difference between being "tolerated" and having my identity (and even my fundamental human rights) respected.

Of course, it is a huge difference, and that's precisely the point: otherwise respect and tolerance would be interchangeable, but my point is that they are not.

But there's also a huge difference between people's identities and **opinions**.

Opinions don't have feelings, people do. I have friends who I deeply respect, but not necessarily all their opinions, that's different. A friend of mine doesn't believe humans have actually gone into space. Can anybody demand that I respect that opinion? That would be demanding the impossible, like demanding me to like onions; I just can't.

> For example, as a transgender woman, I don't want my identity to be simply "tolerated".

But the document isn't demanding the respect of other people's identities, it's demanding respect of other people's **opinions**, that's different.

If the document said:

 * Being tolerant of differing opinions and viewpoints
 * Being respectful of other people's identities

I would not be against that.
 
But right now the document is demanding something that is impossible: respecting some things that some people cannot respect (not sincerely).
 
To quote Stephen Fry:

> A demand for respect is like a demand for a laugh, or demands for love, loyalty and allegiance. They cannot be given if not felt.

**Comment by klaude** [comment]
To me, respect implies empathy towards someone's differing opinions, viewpoints, and experiences. Tolerance implies an acknowledgement of those things. The former is stronger than the latter. Acknowledgement is important, but it's a small step towards inclusivity. Respect and empathy are core parts of a positive and harassment-free experience, far moreso than tolerance. Our opinions rarely come from a vacuum. Respect for others' opinions imply knowing the context around those opinions, which leads to greater understanding and stronger communities as a result. 

> But right now the document is demanding something that is impossible

The document doesn't demand respect. That section provides examples of what contributes to a positive community environment. I feel like you're focusing on demand where none exists. @CoralineAda makes a good point about the definition of respect in this context. Perhaps that needs clarifying to make it clear what Contributor Covenant's intent is. On the other hand this feels like straying into semantic weeds. 

Re: Stephen Fry and the successful efforts to [change Cambridge's free speech policy along similar lines](https://www.bbc.com/news/education-55246793). I think the key difference between Contributor Covenant and Cambridge's policies are CC is an opt-in contract for project maintainers that addresses needs of marginalized members of the tech community. What works for Cambridge may not work here.

**Comment by felipec** [comment]
> To me, respect implies empathy towards someone's differing opinions, viewpoints, and experiences.

I disagree. I can be emphatic towards someone who believes the Earth is flat. That doesn't mean I respect his opinion.

> Tolerance implies an acknowledgement of those things.

No. Tolerance is more than acknowledgement, it's allowing those opinions to exist and be expressed. It's a very low bar, but yet many people fail at that.

> Respect for others' opinions imply knowing the context around those opinions, which leads to greater understanding and stronger communities as a result.

I can know the context of why somebody believes the Earth is flat, but that's not going to make me respect it.

> The document doesn't demand respect. That section provides examples of what contributes to a positive community environment.

OK. But then the next section talks about enforcement. What happens when somebody is not respectful, shows no empathy, does not give feedback gracefully, does not accept responsibility, and ignores what's best for the community? Should his/her behavior simply be ignored by the leadership?

> I think the key difference between Contributor Covenant and Cambridge's policies are CC is an opt-in contract for project maintainers that addresses needs of marginalized members of the tech community.

I disagree. Marginalized members of the tech community are not the only people that need to feel welcome. **Everyone** needs to feel welcome, and everyone needs to obey the code of conduct, not just leaders.

> What works for Cambridge may not work here.

Once again I respectfully disagree. Most of the intellectuals who objected to the demand for respect where not Cambridge alumni, but people who advocate for freedom of speech.

The reason why tolerance of opinions is important is that it allows the most important kind of diversity: diversity of opinions.

**Comment by CoralineAda** [comment]
Tolerance is the privilege of the powerful: it is the granting of permission to deviate from the norms of the majority. And it comes with the threat that this permission can be revoked at any time. It centers the comfort of the majority. Asking the powerless to be tolerant is asking them to grudgingly endure their oppression.

> "Intergroup toleration is a requirement for living with diversity and actively promoted by local, national, and international bodies. However, although psychological researchers have extensively considered the implications of being discriminated, little is known about the psychological consequences of being tolerated. In this article, we argue that beyond the freedoms implied by tolerance, being “merely” tolerated also implies social identity threats that compromise specific psychological needs (belongingness, esteem, control, certainty). We further consider the psychological consequences of being tolerated at the personal, interpersonal, and intergroup levels and consider factors that may moderate the impact of being tolerated for minority outcomes. Taken together, this work provides the first theoretical argument and overview of what it means to be tolerated by considering the negative implications of toleration in diverse nations." 

> [The Negative Implications of Being Tolerated: Tolerance From the Target’s Perspective](https://journals.sagepub.com/doi/10.1177/1745691619897974)  
> Verkuyten, Maykel, Kumar Yogeeswaran, and Levi Adelman. “The Negative Implications of Being Tolerated: Tolerance From the Target’s Perspective.” Perspectives on Psychological Science 15, no. 3 (May 2020): 544–61. https://doi.org/10.1177/1745691619897974.

**Pull request closed without merging**
