### PR TITLE
Make Swiss Post an adopter of contributor covenant

### PR DESCRIPTION
**Pull request by mu88**

### CODE REVIEW

**Review by sarhm — APPROVED** [review]

**Comment by mu88** [comment]
@CoralineAda can you do the review?

**Comment by CoralineAda** [comment]
@mu88 I don't see the code of conduct in the repo you listed, can you point me to where it is? Thanks!

**Comment by mu88** [comment]
@CoralineAda Of course, [here you go](https://github.com/EthicalSource/contributor_covenant/pull/1047/files#diff-784b417338c5f93493952aec9557bff2ad295c3c88a7a258e3c41d5fe94c60b4) 👍🏻

**Review by CoralineAda — APPROVED** [review]
Wonderful, thank you!

**Pull request merged**
