### PR TITLE
add Kickoff

### PR DESCRIPTION
**Pull request by mrmartineau**
https://github.com/TryKickoff/kickoff

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in the project?

**Comment by mrmartineau** [comment]
@CoralineAda sorry, its in the `next` branch which we are pushing today, see https://github.com/TryKickoff/kickoff/blob/next/CODE-OF-CONDUCT.md

Thanks

**Comment by CoralineAda** [comment]
Let me know when it’s there and I’ll happily merge. Thanks!

**Comment by mrmartineau** [comment]
Thanks, will do.

**Comment by mrmartineau** [comment]
@CoralineAda we merged last week and I forgot to mention it here. Thanks

**Comment by mrmartineau** [comment]
Great! 👍

**Pull request merged**
