### PR TITLE
Adding Mattermost to Adopters list

### PR DESCRIPTION
**Pull request by aspleenic**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Where can I find the code of conduct here? I peeked in a couple of repos under this org and didn't see one.

**Comment by aspleenic** [comment]
It's under our universal .github file - https://github.com/mattermost/.github/pull/4#pullrequestreview-515037400

**Comment by CoralineAda** [comment]
Thanks PJ!

**Comment by aspleenic** [comment]
No - thank you!

**Review by DvalCaruso — COMMENTED** [review]
adopter

**Pull request merged**
