### PR TITLE
Add GlobaLeaks project to adopters

### PR DESCRIPTION
**Pull request by evilaliv3**
Added GlobaLeaks: https://github.com/globaleaks/GlobaLeaks/blob/main/CODE_OF_CONDUCT.md
Screenshot_2021-01-25 globaleaks GlobaLeaks

### CODE REVIEW

**Review by CoralineAda — CHANGES_REQUESTED** [review]
Can you please add it to the right spot in alphabetical order? Thanks!

**Comment by evilaliv3** [comment]
Ah! i was considered to made it ahahah, let me fix it right away!

**Comment by evilaliv3** [comment]
Done @CoralineAda! thank you for your work!

**Review by CoralineAda — APPROVED** [review]
Thanks so much!

**Pull request merged**
