### PR TITLE
Zup's Projects included

### PR DESCRIPTION
**Pull request by caroldf07**

### CODE REVIEW

**Review by carolinafonsecazup — APPROVED** [review]
LGTM

**Review by CoralineAda — CHANGES_REQUESTED** [review]
Can you please revert the whitespace removal in `static/adopters.csv`?

**Comment by caroldf07** [comment]
@CoralineAda I've changed, can you review again, please?

**Review by CoralineAda — APPROVED** [review]
Wonderful, thanks!

**Pull request merged**
