### PR TITLE
Add Dokku as adopter of CC

### PR DESCRIPTION
**Pull request by josegonzalez**
Also fixed the scheme on the diaspora link

### CODE REVIEW

**Comment by CoralineAda** [comment]
Thanks!

**Comment by josegonzalez** [comment]
No thank you!

**Comment by loleg** [comment]
@josegonzalez I'm afraid I no longer see the the `code_of_conduct.md` ([History](https://github.com/dokku/dokku/commits/0f4774bf60f0c08561466e0e6222eeade1ab3239/CODE_OF_CONDUCT.md)) on the Dokku master branch, only [CONTRIBUTING.md](https://github.com/dokku/dokku/blob/master/CONTRIBUTING.md) which makes no mention of it. Was the CoC dropped by accident?

**Comment by josegonzalez** [comment]
No, I moved it to the [.github](https://github.com/dokku/.github/blob/master/CODE_OF_CONDUCT.md) repo to cover all the codebases in the org vs just the one. Not sure if thats the best way to do it, but it covers the "CoC" portion of the "Community Standards" page in the `dokku/dokku` Insights tab.

**Comment by loleg** [comment]
Oh I see. When I click Insights > CoC it redirects me to the original repo. I guess that is technically sufficient, though as a developer looking at the project on GitHub, it doesn't exactly jump out at me ;-)

**Comment by josegonzalez** [comment]
The sidebar of the repo has a "Code of Conduct" link and - interestingly - the readme on the homepage has a CoC tab as well. Shame we can't have virtual files in the repo, though I understand why that would make browsing repositories confusing.

**Pull request merged**
