### PR TITLE
Translated to Kannada

### PR DESCRIPTION
**Pull request by DeepakChethan**
For issue #423

### CODE REVIEW

**Comment by CoralineAda** [comment]
Thanks! I just put out a call looking for another Kannada speaker to review the translation.

**Comment by 0PoojaPandit0** [comment]
I observed that you could make a couple of changes. 
Instead of ಈವೆಂಟ್ನಲ್ಲಿ in ವ್ಯಾಪ್ತಿ you could use ಕಾರ್ಯಕ್ರಮಗಳಲ್ಲಿ.
I saw a typo  ಬೇಕಾಗಿರುತದೆ  should be written as ಬೇಕಾಗಿರುತ್ತದೆ.
ಮಾನದಂಡಗಳ should be ಮಾನದಂಡನೆಗಳು
Instead of ಹೊಣೆಗಾರಿಕೆಗಳ use ಹೊಣೆಗಾರಿಕೆಗಳು
Instead of ಜಾರಿಗೊಳಿಸುವಿಕ use ಜಾರಿಗೊಳಿಸುವಿಕೆ
Apart from these errors, this looks good to go.

**Comment by CoralineAda** [comment]
@DeepakChethan Let me know when this is ready to go!

**Comment by DeepakChethan** [comment]
I updated the translation @0PoojaPandit0 can you take a look?

**Comment by 0PoojaPandit0** [comment]
It looks good.

**Comment by DeepakChethan** [comment]
@CoralineAda, I think it's ready.

**Comment by CoralineAda** [comment]
This is great, thanks so much!

**Pull request merged**
