### PR TITLE
Minor Fixes On Turkish Translation For Version 2

### PR DESCRIPTION
**Pull request by umutphp**
I have made some minor updates on Turkish translation for version 2.

### CODE REVIEW

**Review by CoralineAda — APPROVED** [review]
Thank you so much!

**Comment by CoralineAda** [comment]
@umutphp There's an error in the TOML directive at the top:

`4:52:55 PM: Error: Error building site: "/opt/build/repo/content/version/2/0/code_of_conduct.tr.md:1:4": EOF looking for end TOML front matter delimiter`

**Comment by umutphp** [comment]
Hi @CoralineAda, 

The bug you mentioned is fixed :).

**Review by CoralineAda — APPROVED** [review]

**Comment by CoralineAda** [comment]
Thanks so much!

**Pull request merged**
