### PR TITLE
Add Japanese translations version 1.4

### PR DESCRIPTION
**Pull request by tomo667a**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Thank you for the hard work! I'm reaching out now to find a native speaker to review the translation.

**Comment by girliemac** [comment]
The translation looks good to me. There one bullet list that I may want to change- 
where it originally says "The use of sexualized language or imagery and unwelcome sexual attention or advances", the Japanese translation doesn't seem to be straightforward.

I would change it to:
性的な意味を含む言葉や画像、迷惑な性的注意や接近

**Comment by tomo667a** [comment]
Thank you for reviewing. I changed it to:
性的な意味を含む言葉や画像、迷惑な性的注意や接近

**Comment by girliemac** [comment]
OK, I kept the last part in the original translation as is, but if I modify it too, I'd say:
性的な駆け引きや接近

How about this? Does it sound more natural?

**Comment by TatchNicolas** [comment]
Sounds way much better to me!

**Comment by CoralineAda** [comment]
Is this ready to merge?

**Comment by girliemac** [comment]
Oops, I said I was gonna make the change but realized it haven't been merged yet, so @tomo667a, can you include the change and commit again? Thank you~~

**Comment by tomo667a** [comment]
Thanks, I updated the patch.

**Comment by tomo667a** [comment]
@CoralineAda I think this patch is ready to merge.

**Comment by CoralineAda** [comment]
Thank you so much!

**Pull request merged**
