### PR TITLE
Add All Algorithms to adopters

### PR DESCRIPTION
**Pull request by abranhe**
Add The All ▲lgorithms project to Contributor Covenant!

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in this repo. Am I missing it?

**Comment by abranhe** [comment]
Hi, @CoralineAda we are working on it, but it will be for sure in there!!!!

**Comment by CoralineAda** [comment]
OK, ping me when it’s in place and we’ll update the adopters list then. Thanks!

**Comment by abranhe** [comment]
@CoralineAda the [code of conduct](https://github.com/abranhe/algorithms/blob/master/.github/code-of-conduct.md) in this now on the repo!

**Comment by CoralineAda** [comment]
Looks great!

**Comment by abranhe** [comment]
Happy that the pull request got merged in!

**Pull request merged**
