### PR TITLE
Change "other's" to plural possessive

### PR DESCRIPTION
**Pull request by wvu-r7**
Since we're talking about more than one person, potentially.

This could be changed to "another person's" or "other people's" or something or other (a couple suggestions from @jlee-r7 :). Could drop the word altogether.

https://github.com/rapid7/metasploit-framework/pull/6437

### CODE REVIEW

**Comment by CoralineAda** [comment]
Can you please change the .txt and .html files as well? Thanks!

**Comment by wvu-r7** [comment]
Agh, I shouldn't have used the in-browser editor. One sec. :)

**Comment by wvu-r7** [comment]
Turns out I didn't even edit the actual files. My bad!

**Comment by CoralineAda** [comment]
Fixed in 1.4

**Comment by wvu-r7** [comment]
Thank you!

**Pull request closed without merging**
