### PR TITLE
Make miscellaneous changes

### PR DESCRIPTION
**Pull request by ruafozy**
I'd like to have a different pull request for each commit, but GitHub
doesn't seem to allow that.  Sorry if that's inconvenient.

One commit removes the term "private harassment".  Having "private
harassment" as a forbidden behaviour conflicts with the "Scope" section.
Therefore, one of these two things has to be sacrificed; and I think the
"Scope" section is the more important of the two.

Another commit removes terms such as "unacceptable behaviour", which could
be interpreted very broadly and could refer to actions that are not
mentioned in the code.  It replaces them with terms such as "breaches of
this Code".

Lastly, another commit replaces wording which implies that there are
behaviours which are forbidden but unspecified.  If an implementation wants
to forbid other behaviours, it can simply add them to the list.

### CODE REVIEW

**Comment by achadwick** [comment]
I really think your proposal would add too many loopholes.

It is possible to harass in private at a public convention at which one is a nominated representative of a project. It is possible to leverage one's power as a project lead to harass privately, or at least have it excused by project maintainers. Both behaviours are toxic to groups even when they happen in private (it just takes longer), and I believe that both are indefensible amongst people signing up to a code like this.

So, :-1: on removing "private", just for those reasons. I tend to go a little further myself, feel free to disagree.

Private or off-piste harassment campaigns by members ought to be grounds for CoC action too, given their extreme potential for demolishing a positive environment. If anything the scope section should be expanded to better cover patterns of straight-up targeted abuse. I'd be happy with adding "[i]n the specific and limited case of targeted harassment or abuse, this Code of Conduct may apply generally while an individual might represent the project".

The standards section should remain a guideline for what is encouraged and what is deemed unacceptable. The responsibilities section would continue to be effective with language that discusses defined inappropriate behaviour. I'm unhappy about introducing pseudolegalistic language such as "breaches" or authoritarian wording like "forbids".

Introducing the test "breach the code AND which they deem inappropriate" seems like another loophole. Requiring reporters to determine what makes a "breach" and not merely _abuse, harassment or (something defined earlier as) inappropriate_ seems like a good way of discouraging reports.

**Comment by ruafozy** [comment]
> I'm unhappy about introducing pseudolegalistic language such as "breaches"

As far as I can see, the word "breaches" is no more and no less legalistic
than the Code itself.

> Requiring reporters to determine what makes a "breach" [...] seems like a good way of discouraging reports.

I disagree.  All the reporter has to do is read the Code.

> abuse, harassment or (something defined earlier as) inappropriate

This text is interesting, for two reasons.  Firstly, it doesn't appear in
the file `code_of_conduct.md` (either my version or the original).

Secondly, the interpolated text (viz. "(something defined earlier as)") is
an interpretation on your part.  There is an alternative interpretation, a
perfectly natural one, in which the interpolated text is not implied.  This
alternative interpretation gives wide latitude to the project maintainers,
allowing them to ban contributors for anything "inappropriate", which may
include behaviours that are not mentioned in the Code of Conduct.

**Comment by mprelude** [comment]
I don't agree with removing private harassment, I do agree with clarifying 'harassment'. Is somebody who is caught up in an on-topic debate taking it to Twitter considered to be 'harassing' the other participants in the debate? The definition should include a requirement for the 'harassed' party to make it clear to the 'harasser' that they don't want to be contacted by that person outside of the project spaces.

I agree with the idea of limiting potential violations to the CoC (the term 'breach' is usually specific to private contract law, and as this isn't a legal document, I'd suggest not using it).

**Comment by strand** [comment]
I don't believe these changes add any significant value, and may actually weaken the Covenant. @CoralineAda I recommend you close this Pull Request.

**Pull request closed without merging**
