### PR TITLE
Translation for Marathi Language

### PR DESCRIPTION
**Pull request by ksinkar**
Marathi is one of the heirs to the Prakrit language.
मराठी ही प्रकृत भाषेची वारसांपैकी एक आहे।

https://en.wikipedia.org/wiki/Prakrit
https://en.wikipedia.org/wiki/Hemachandra#Siddha-Hema-%C5%9Aabdanu%C5%9B%C4%81%C5%9Bana
https://en.wikipedia.org/wiki/Maharashtri_Prakrit
https://en.wikipedia.org/wiki/Marathi_language

### CODE REVIEW

**Comment by CoralineAda** [comment]
Thank you so much! Putting out a call for native speakers to review the translation. If you know anyone, please feel free to tag them in.

**Comment by ksinkar** [comment]
@manojshevate @pruthanagrikar @prutha-nagrikar @pallavik @nikhilkadadi @pallavikadadi

Please have a look and give your feedback.

**Comment by ksinkar** [comment]
@amrutamarch20 Please give feedback.

**Review by manojshevate — APPROVED** [review]
Looks good to me!

**Comment by CoralineAda** [comment]
@ksinkar ready for me to merge?

**Comment by ksinkar** [comment]
@CoralineAda Yes.

**Comment by ksinkar** [comment]
@knightsamar Please review.

**Comment by ksinkar** [comment]
@CoralineAda Ready for you to merge. Please go ahead.

**Comment by CoralineAda** [comment]
Thanks so much!

**Pull request merged**
