### PR TITLE
added sex as a protected characteristic

### PR DESCRIPTION
**Pull request by corinna000**
It's no secret that women in technology are in the minority both in business and in open source. By adding "sex" as a protected characteristic, this change will make it clear that contributors cannot be discriminated against on the basis of their sex—a problem recognized in many developer cultures.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I feel like this is already covered by "sexual identity". Sex as a distinct term can be construed as being an artifact of biological essentialism. Thoughts?

**Comment by corinna000** [comment]
Wikipedia lists sexual identity as "Sexual identity is how one thinks of oneself in terms of to whom one is romantically or sexually attracted." and not as one's biological sex. As for biological essentialism, I think that category can be protected without having to address the political conflicts around essentialism.

**Comment by CoralineAda** [comment]
That’s a really bad definition of sexual identity. It has zero to do with orientation…

Would you mind opening an issue so the community can weigh in on this discussion?

**Comment by corinna000** [comment]
Gladly. I will do so tonight.

**Pull request closed without merging**
