### PR TITLE
add SOULs in adopters.csv

### PR DESCRIPTION
**Pull request by POPPIN-FUMI**

### CODE REVIEW

**Comment by POPPIN-FUMI** [comment]
Added SOULs (https://souls.elsoul.nl/) as an adopter

**Comment by CoralineAda** [comment]
You don't have any contact information in the enforcement section. Search for ` [INSERT CONTACT METHOD]`

**Review by puchongcnxx29 — COMMENTED** [review]
werapon16@hotmail.com

**Review by puchongcnxx29 — APPROVED** [review]
##Bb12344321

**Comment by POPPIN-FUMI** [comment]
> You don't have any contact information in the enforcement section. Search for ` [INSERT CONTACT METHOD]`

I updated it. 
https://github.com/elsoul/souls/blob/master/CODE_OF_CONDUCT.md
Thank you!

**Review by CoralineAda — APPROVED** [review]

**Comment by CoralineAda** [comment]
Thanks!

**Pull request merged**
