### PR TITLE
Small improvement of Swedish language translation

### PR DESCRIPTION
**Pull request by Ainali**
# Contributor Covenant translation improvement

## Language
Swedish

Ping @janderssonse and @jenniferskoglund who worked on Swedish before, is my contribution an improvement?

### CODE REVIEW

**Comment by janderssonse** [comment]
A great improvement @Ainali . @CoralineAda as one of originators of the first Swedish translation, I certainly think @Ainali s enhancement suggestions are spot on and as such could be merged.

On a sidenote, and while at it, @Ainali , do you have any suggestions regarding the current title translation: Contributor Covenant Code of Conduct ->"Gemenskapens uppförandekod vid bidrag" sounds a bit less perfect imho, but I don't have much better suggestions coming up.

**Comment by Ainali** [comment]
> On a sidenote, and while at it, @Ainali , do you have any suggestions regarding the current title translation: Contributor Covenant Code of Conduct ->"Gemenskapens uppförandekod vid bidrag" sounds a bit less perfect imho, but I don't have much better suggestions coming up.

That's a great question. How do you feel about "Bidragsgivaröverenskommelse Uppförandekod"? It's a more literal translation but also an odd stapling of nouns. (Which, to be fair, the English original also is.)

**Comment by janderssonse** [comment]
> > On a sidenote, and while at it, @Ainali , do you have any suggestions regarding the current title translation: Contributor Covenant Code of Conduct ->"Gemenskapens uppförandekod vid bidrag" sounds a bit less perfect imho, but I don't have much better suggestions coming up.
> 
> That's a great question. How do you feel about "Bidragsgivaröverenskommelse Uppförandekod"? It's a more literal translation but also an odd stapling of nouns. (Which, to be fair, the English original also is.)

Good,, Let's base it on that suggestion,  but imho aim for an slightly less literal translation and look to how we would name it in Swedish, had we come up with it? "Uppförandekod för bidragsgivare" or "Bidragsgivares uppförandekod". Of these I would suggest for the former so I suggest then "Uppförandekod för bidragsgivare".  Would that be an improvement?.  -"Ärade kollegor, idag ska vi högaktningsfullt läsa igenom "Uppförandekod för bidragsgivare", vX.Y.Z. Yes, I think it would work fine?

**Comment by Ainali** [comment]
> Good,, Let's base it on that suggestion, but imho aim for an slightly less literal translation and look to how we would name it in Swedish, had we come up with it? "Uppförandekod för bidragsgivare" or "Bidragsgivares uppförandekod". Of these I would suggest for the former so I suggest then "Uppförandekod för bidragsgivare". Would that be an improvement?. -"Ärade kollegor, idag ska vi högaktningsfullt läsa igenom "Uppförandekod för bidragsgivare", vX.Y.Z. Yes, I think it would work fine?

I agree that your suggestions are easier to say and sound more natural. I am, however, a bit at unease with dropping 50% of the project name in the translation. Translated back, it would be "Code of Conduct for Contributors". 

Given that the word "Covenant" must be assumed to have been carefully selected for the project, I suggest coming up with something that carries over that weight. Unfortunately, I have no better suggestion, so perhaps this is the least bad solution?

**Comment by janderssonse** [comment]
> > Good,, Let's base it on that suggestion, but imho aim for an slightly less literal translation and look to how we would name it in Swedish, had we come up with it? "Uppförandekod för bidragsgivare" or "Bidragsgivares uppförandekod". Of these I would suggest for the former so I suggest then "Uppförandekod för bidragsgivare". Would that be an improvement?. -"Ärade kollegor, idag ska vi högaktningsfullt läsa igenom "Uppförandekod för bidragsgivare", vX.Y.Z. Yes, I think it would work fine?
> 
> I agree that your suggestions are easier to say and sound more natural. I am, however, a bit at unease with dropping 50% of the project name in the translation. Translated back, it would be "Code of Conduct for Contributors".
> 
> Given that the word "Covenant" must be assumed to have been carefully selected for the project, I suggest coming up with something that carries over that weight. Unfortunately, I have no better suggestion, so perhaps this is the least bad solution?

I think the intent is more important than the literal translation so I don't 100% agree here.. But as always, when two slightly different opinions meet lets see if we can ask a third person into this. @mattiasaxell - I noticed you showed interest in the initial Swedish translation here https://github.com/EthicalSource/contributor_covenant/pull/1143 

So, asking you kindly if you would like to give some input on the header translation discussion and proposals given from me and Jan. Should we go for a more literal, or a more intent driven header translation as discussed. Or should we even keep the current one?

**Comment by janderssonse** [comment]
Nytt försök baserat på Jans förslag: Överenskommelse om uppförandekod för bidragsgivare @Ainali @danneleaf vad tror ni?

**Comment by danneleaf** [comment]
> Nytt försök baserat på Jans förslag: Överenskommelse om uppförandekod för bidragsgivare @Ainali @danneleaf vad tror ni?

Jag tycker att ni knådat ihop en bra översättning där och röstar på "Överenskommelse om uppförandekod för bidragsgivare"

**Comment by mattiasaxell** [comment]
@Ainali I like your suggestions and @janderssonse yes "Överenskommelse om uppförandekod för bidragsgivare" is a really good improvement!

**Comment by janderssonse** [comment]
All agreed then?. "Swedish consensus has been reached"? Would you update the header in this pr too @Ainali and then we could ask the maintainers for merge!

**Comment by Ainali** [comment]
Done! Ready to merge.

**Comment by janderssonse** [comment]
Great! @CoralineAda and other maintainers, this one is 100% ready to merge.

**Review by CoralineAda — APPROVED** [review]
Wonderful, thank you all for the work!

**Pull request merged**
