### PR TITLE
Simplified Chinese Version

### PR DESCRIPTION
**Pull request by tigercosmos**
It's the simplified Chinese version.

### CODE REVIEW

**Comment by abc612008** [comment]
Is that just translation from traditional chinese? cuz some words look odd for me, such as "专案".

**Comment by tigercosmos** [comment]
@abc612008 　I changed some terms, and please feel free to give me some advice.

**Comment by abc612008** [comment]
It looks much better now. However, some words are still odd.
Some advice:
* "都免于骚扰。。". there is a redundant “。”.
* "酸民" is not widely used in SImplified Chinese. I seldom hear it.
* "项目维护者有权力及责任去...". I think "权利" is better than "权力" here.
* "可以透过[在此放入EMAIL]". Using "通过" instead of "透过" would be better.
* "暂时或是永久的取消". "的" should be "地" according to grammar.
Other than these, the translation looks perfect for me.

**Comment by tigercosmos** [comment]
Thanks for your advice, I fixed typo and changed some words mentioned above.

**Comment by abc612008** [comment]
Sorry, I just found another small mistake. In "具体执行的方针", "方针" should be "方案". "方针" is more like a general plan or direction instead of a specific one.

**Comment by tigercosmos** [comment]
> Sorry, I just found another small mistake. In "具体执行的方针", "方针" should be "方案". "方针" is more like a general plan or direction instead of a specific one.

@abc612008  I don't agree that.  The original is "Further details of specific enforcement policies may be posted separately." Translating the word "policies"  to "方针" is precise. The word "方案" should be translated by "proposal" or "plan".

**Comment by abc612008** [comment]
You are right. "方针" is more appropriate choice according to the original text.

**Comment by tigercosmos** [comment]
So, should I create two additional files?

**Comment by CoralineAda** [comment]
Yes, please follow the instructions here: https://github.com/ContributorCovenant/contributor_covenant#translating <https://github.com/ContributorCovenant/contributor_covenant#translating>

**Comment by tigercosmos** [comment]
@CoralineAda Done. Please check. Thanks.

**Comment by CoralineAda** [comment]
Nice work, thank you so much!

**Pull request merged**
