### PR TITLE
Add Meridian.

### PR DESCRIPTION
**Pull request by nicholaswyoung**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi Nicholas! It's important for you to put a copy of the Contributor Covenant in your repo so that you can specify the email address that people should use to contact you.

**Comment by nicholaswyoung** [comment]
Can do! I linked it in the README, and thought that was the preferred way. 

Is there a standard name for the file?

**Comment by CoralineAda** [comment]
CODE_OF_CONDUCT.md

**Comment by nicholaswyoung** [comment]
:+1: Got it done: https://github.com/UntilNow/meridian/blob/master/CODE_OF_CONDUCT.md

**Pull request merged**
