### PR TITLE
Add Yii to adopters list

### PR DESCRIPTION
**Pull request by vjik**
# Contributor Covenant Adoption

## Project name
Yii Framework

## Project repository
Yii3 is package-based framework. All packages based on https://github.com/yiisoft/package-template
Example of packages: [yiisoft/di](https://github.com/yiisoft/di), [yiisoft/mailer](https://github.com/yiisoft/mailer/).

## Link to code of conduct in your project's repo or documentation
[Code of conduct](https://github.com/yiisoft/package-template/blob/master/.github/CODE_OF_CONDUCT.md)

## Check your work!
Please double-check that you inserted the contact method for reporting incidents in the template. (Search the document for `sergei@predvoditelev.ru`)

*Thank you!*

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi @vjik , I notice that you're using an older version of Contributor Covenant (1.4). I'd strongly recommend updating to v2.1, available here: https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by vjik** [comment]
> Hi @vjik , I notice that you're using an older version of Contributor Covenant (1.4). I'd strongly recommend updating to v2.1, available here: https://www.contributor-covenant.org/version/2/1/code_of_conduct/

Agree. We already adapt version 2.1 in [our package template](https://github.com/yiisoft/package-template/blob/master/.github/CODE_OF_CONDUCT.md) and we will gradually do this for all our packages.

**Comment by vjik** [comment]
@CoralineAda We update Contributor Covenant to version 2.1 in all our packages.

**Review by CoralineAda — APPROVED** [review]
Great, thank you!

**Pull request merged**
