### PR TITLE
Added all the projects from The Guild to the list of adopters

### PR DESCRIPTION
**Pull request by tvvignesh**
Added projects from the guild to the list of adopters of Contributor Covenant: https://github.com/the-guild-org/Stack/

### CODE REVIEW

**Comment by CoralineAda** [comment]
Thanks so much! But you need to add a reporting email or other mechanism to the document (see where it says "[INSERT CONTACT METHOD]").

**Comment by tvvignesh** [comment]
@CoralineAda Thanks for the review. Have updated the relevant repos with the email ID. Hope it looks good now.

**Review by Madsadglad — APPROVED** [review]
😃

**Comment by Madsadglad** [comment]
😃

**Review by Madsadglad — APPROVED** [review]

**Comment by Madsadglad** [comment]
😁

**Review by Madsadglad — APPROVED** [review]
😎

**Comment by popeda97** [comment]
tvvignesh:patch-2

**Review by CoralineAda — APPROVED** [review]

**Pull request merged**
