### PR TITLE
Polish translation for v1.4 + some other fixes

### LINKED ISSUE #239: Version 1.4 Polish Translation
Version 1.4 needs a Polish translation. See the diff at https://github.com/ContributorCovenant/contributor_covenant/blob/master/diffs/1_3_vs_1_4.patch. 

Attn @Kwpolska @michalsapka

### PR DESCRIPTION
**Pull request by Kwpolska**
Fixes #239.

cc @jaen @michalsapka @CoralineAda 

Fixes welcome. Some things sound awkward, I didn’t have better ideas how to write it.

Also, automated generation of  `.txt` and `.htm` files could be really useful.

### CODE REVIEW

**Comment by jaen** [comment]
Hi, here's my input based on your translation. /cc @michalsapka @CoralineAda 

https://gist.github.com/jaen/4efd16b6c74cbc85ec08

I don't think you actually can do PR-ception on Github (that is add your proposed changes to a foreign PR) so instead I put in a gist. It consists of four files - markdown formatted document, markdown's document source, the diff between your version and mine and - most importantly - the rationale. Hope it's readable in this format.

I strived to document and prop up every change I made so you could understand why I chose to suggest alternate wording. The rationale is written in English (with Polish words and phrases explained as much as possible) so Coraline can see whether there is any misinterpretation of her intent or not.
@CoralineAda I suggest to at the very least look at the issue I have in interpreting `private information` (Ctrl+F `informacji osobistych` in the rationale) and offering your take on it - basically whether this means only personally identifiable information (revealing of which could result in actual IRL inconvenience or abuse), or any personal information on top of that the person in question would want to keep secret.

That took a while (due to the need to consult sources and such), so I hope it is helpful.
Now, back to my thesis.

**Comment by CoralineAda** [comment]
Seems  very thorough and I didn't disagree with any of your interpretations. @Kwpolska let me know when you're all merged in.

**Comment by Kwpolska** [comment]
Merged. I fixed one leftover instance of *otoczenia* and one awkward sentence (and I faked the commit attribution). This may now be merged.

**Comment by jaen** [comment]
@Kwpolska
So that actually were half-pauses (`–`) not pauses (`—`), huh? Dayum, wanted to have correct typography, mixed punctuation up. I will not live this down : |
Good catch, though!

Though now I look at this PR I see two issues:

* I think I can agree about leaving `commits` as `commitów`, it feels quite natural. It's just probably having to do that in thesis that set off my rebellious phase of translating everything (they require you to translate `framework` to `zrąb aplikacji`, would you imagine?).   
That said, you seem to have left `commitów (ang. _commit_)` in the PR. Is that intentional or an omission? I see you changed that stray `otoczenia` and half-pauses into pauses, so it may very well be intentional, but it's better to verify - I have no qualms about it being an Anglicism in this case since, as you say, it's in common usage.

* the sentence you've changed is:
```
* Używanie języka i grafik o podtekście seksualnym, okazywanie
  niepożądanego zainteresowania seksualnego oraz zaloty,
```
yes? I think you're right to have done so, I didn't notice it then, but my version reads:
```
* Używanie (...) niepożądanego zainteresowania seksualnego lub zalotów,
```
which is mighty dumb of me to have phrased it so. Verb `using` with nouns `attention` or `advances` makes literally no sense. Good catch! Though you messed up that case - `zaloty` (nominative) should've been `zalotów` (genitive).

* I only made a markdown version and you only updated the markdown version. Don't plaintext and HTML versions need to be updated as well? Or is there some automated tooling in place that takes markdown in and spits out HTML and text, so only this version needs to commited, or should that be updated by either of us?

Your thoughts?

@CoralineAda
> Seems very thorough and I didn't disagree with any of your interpretations.
Heh, yeah. I'm the type to believe in formal correctness and Haskell-level type system P ;  
I thought you might have some differing interpretations (especially on that thing I pointed out), but if we're good on that, then nice!

Also, please hold on with merging for a while as we get those three issues above straight.

**Comment by Kwpolska** [comment]
> So that actually were half-pauses (–) not pauses (—), huh? Dayum, wanted to have correct typography, mixed punctuation up. I will not live this down : |

Don’t worry, correct typography is hard and opinionated. And there are [lots of things](http://poledyt.amu.edu.pl/download/Janusz%20Nowacki.pdf) you can’t do in Markdown files. (speaking of which, what do you write your thesis in?)

> Though you messed up that case - zaloty (nominative) should've been zalotów (genitive).

„okazywać zaloty” and „używać zalotów” does not make sense (at least to me). I meant something like this (added Oxford comma):

> Wśród przykładów […] **są**:

> * Używanie języka i grafik o podtekście seksualnym, okazywanie
  niepożądanego zainteresowania seksualnego, oraz **zaloty**,

---

>I think I can agree about leaving commits as commitów, it feels quite natural. It's just probably having to do that in thesis that set off my rebellious phase of translating everything (they require you to translate framework to zrąb aplikacji, would you imagine?).

Oh what. I would understand *szkielet* or *platforma programistyczna* (via Wikipedia), but this is complete nonsense. I’ll leave *zmiany w kodzie* as-is.

And this is why people hate academia.

> I only made a markdown version and you only updated the markdown version. Don't plaintext and HTML versions need to be updated as well? Or is there some automated tooling in place that takes markdown in and spits out HTML and text, so only this version needs to commited, or should that be updated by either of us?

I just forgot about all that. Should be automated, but isn’t. I’ll fix it now.

This is ready to be merged.

**Comment by jaen** [comment]
@Kwpolska 
Yeah, markdown is pretty austere in the typography department - I wanted to have proper punctuation at the very least.  
Regarding the thesis - I'm writing it in LaTeX; I can't stand neither Word nor Libre Office - both due to visual formatting (over control sequences) being annoying and due to it sucking at proper typography. I'm probably not as well versed in it as Knuth was after he wrote TeX, but I like to make at least a bit of effort to have it look good. Also, thanks a lot for the link, it seems helpful!

> „okazywać zaloty” and „używać zalotów” does not make sense (at least to me). I meant something like this (added Oxford comma)

Okay, I see your point. I kind of assumed the original case was correct and didn't think twice about it. But I don't think the comma is correct there, cf. http://sjp.pwn.pl/poradnia/haslo/przecinek-a-spojnik-b-b-oraz-b-b;11547.html. But since `oraz` is somewhat unclear, may I suggest
```
Używanie języka i grafik o podtekście seksualnym, okazywanie niepożądanego zainteresowania seksualnego, a także zaloty,
```
instead? What do you think?

> but this is complete nonsense
It totally is, but also it's true - http://devpytania.pl/questions/17586/framework-tumaczenie (Politechnika Śląska here, not smart enough for UW). And unfortunately `szkielet` and `platforma` both have their problems - `szkielet` is also a translation for `scaffolding` and `boilerplate`, while `platforma` is also a translation for `platform` (as in `the JVM platform` which is not synonymous to framework IMO). Hence the need for a distinct term, but I'm not sure why there is a prefrence for the awkward sounding - if semantically sensible - `zrąb aplikacyjny`. I'd just use `framework` and live with it, but I can't : |

And yeah, academia sucks. I learned almost nothing during my courses. Only this year's elective about IT systems architecture was a thing that was good, I learned some and would endorse. The rest? My algorithms professor mistook a functional programming language with a structural programming language (because you know, it has functions as a building block as well) when I have written my report on sorting algorithms with example in Haskell : |

> mogły by

I missed that the first time? Whoops. Good thing you noticed it now : )

@CoralineAda 
We just need to reach consensus on the first unacceptable behaviour example and we're set I think.

**Comment by Kwpolska** [comment]
> Regarding the thesis - I'm writing it in LaTeX; I can't stand neither Word nor Libre Office - both due to visual formatting (over control sequences) being annoying and due to it sucking at proper typography. I'm probably not as well versed in it as Knuth was after he wrote TeX, but I like to make at least a bit of effort to have it look good. Also, thanks a lot for the link, it seems helpful!

[I had](https://dl.dropboxusercontent.com/u/1933476/ContributorCovenantPL.tex) to [do this](https://dl.dropboxusercontent.com/u/1933476/ContributorCovenantPL.pdf). (mostly auto-generated via pandoc; probably not perfect, but good enough to me)

> Używanie języka i grafik o podtekście seksualnym, okazywanie niepożądanego zainteresowania seksualnego, a także zaloty,

Fixed.

**Comment by jaen** [comment]
> I had to do this. (mostly auto-generated via pandoc; probably not perfect, but good enough to me)

Wow <3 Mad respect for doing it that way. Incidentally, this could be a good idea to write this in one format (be it markdown, LaTeX, whatever) and then pandoc it to other formats. That way all formats would be maintained in sync.

> Fixed

Then it LGTM too.

@CoralineAda
We're both in agreement on the wording now. Unless you have anyone else you would want to pass it through then I think it's ready for merging.

**Comment by Kwpolska** [comment]
>  Wow <3 Mad respect for doing it that way. Incidentally, this could be a good idea to write this in one format (be it markdown, LaTeX, whatever) and then pandoc it to other formats. That way all formats would be maintained in sync.

pandoc is *far* too heavy for this. Any random Markdown compiler to go to .html is enough, and the .txt version is useless anyway (some little bits of Markdown formatting should not be a problem for anybody). In other words: we could use [any static site generator](https://getnikola.com/), or put it on GitHub Pages and have their servers compile it with Jekyll.

**Comment by jaen** [comment]
Right, that makes sense - it's certainly simpler and easier to set-up. I probably just fanboy'd a bit because of LaTeX + Haskell (pandoc). Anyway, this seems like a good idea,

**Comment by Kwpolska** [comment]
Off-topic, but the original code produced by Pandoc required some manual cleanup to make more sense.

**Comment by CoralineAda** [comment]
Thanks for the great effort!

**Comment by jaen** [comment]
You're welcome; it's always nice to put my language-OCD side to some use  : )

**Pull request merged**
