### PR TITLE
Add bullying to the list of unacceptable behavior

### PR DESCRIPTION
**Pull request by johana-star**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me.

**Comment by strand** [comment]
@CoralineAda What do you think about this change?

**Review by itsromack — APPROVED** [review]

**Comment by strand** [comment]
@itsromack are you a maintainer? I've gotten no indication from @CoralineAda as to wether or not she would accept a change along these lines.

I would love for these changes to be rejected or to resubmit if this content would be accepted.

**Comment by philips** [comment]
What is the status of this PR? I think this is a worthwhile addition.

**Review by ghost — COMMENTED** [review]
[bullying ]()

**Comment by ghost** [comment]
> b

**Pull request closed without merging**
