### PR TITLE
Add SuiteCRM to adopters

### PR DESCRIPTION
**Pull request by samus-aran**
Hi There,

Would like to add SuiteCRM to your list of adopters :+1:

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in the repo… Where is it stashed?

**Comment by samus-aran** [comment]
Hi @CoralineAda. Its currently in hotfix branch prior to pulling it into master (following release process), schedule next release is week ending of 14th July (next week).

https://github.com/salesagility/SuiteCRM/blob/hotfix/CODE_OF_CONDUCT.md

But we have also posted it on our wiki and linked it in the README.md on the hotfix branch.

https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM#Code_of_Conduct
https://github.com/salesagility/SuiteCRM/tree/hotfix

Do you want us to wait until it is in the master before making this PR?

Thanks

**Comment by CoralineAda** [comment]
Yes, please ping me once it’s merged. Thanks!

**Comment by sadeghrajabi** [comment]
تنک

**Pull request closed without merging**
