### PR TITLE
Update adopters.csv

### PR DESCRIPTION
**Pull request by ghost**
added Array.io

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in any of that org's repositories or on the web site. Can you provide links?

**Comment by enaredzic** [comment]
Dear Caroline,
We are developing our network and its temporarily set as private repo. I
will send you an email once we open it for public so that we can proceed.

Best
Ena Redzic

**Comment by ghost** [comment]
Dear Caroline,

I forked it and I have it in our private repo. Now, I am rereading your
message here and I am a bit confused. Could you please refer me to a site
that specifically explains what type of code should be posted on our
website?

Best,
Ena

**Comment by CoralineAda** [comment]
Your code of conduct for a public project should be in a prominent place, like in a CODE_OF_CONDUCT.md file. If you’re an organization with multiple repos, the code of conduct can be linked from each project’s README and placed in an easy-to-find place on your org’s website.

And it’s Coraline, not Caroline. :)

**Comment by ghost** [comment]
Thank you for the info, Coraline.
Apologies, the auto-correct is not always useful. :)

Ena

**Comment by CoralineAda** [comment]
I renamed 'master' to 'release', so you'll need to rebase and reopen this PR.

**Pull request closed without merging**
