### PR TITLE
Add political beliefs to protected traits.

### PR DESCRIPTION
**Pull request by mprelude**
Please see rich diff, my editor likes to trim trailing whitespace.

Added political beliefs to the group of traits which we should protect from discrimination. Liberals, conservatives and libertarians should all feel welcome in a shared collaberation space.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I've gone back and forth on including political beliefs. The point is to call out specific marginalized populations that are frequent targets for abuse, and I'm not convinced that either liberals/progressives or conservatives/libertarians qualify as marginalized groups. Open to discussion.

**Comment by Gorcenski** [comment]
FWIW, I think that "political" beliefs could be a valuable addition, but not because of the conservative/liberal/libertarian taxonomy. Rather, it is worthwhile to note that there are areas of the world where political oppression is very real. I don't think that in Western culture liberals, conservatives, or libertarians are particularly oppressed, and I am otherwise wary that this language could potentially be applied as a trump card to override other factors.

**Comment by CoralineAda** [comment]
Do you not feel that this is covered by “personal or political attacks”?

**Comment by Gorcenski** [comment]
I'm on the fence, really. I could envision some interpretations of behaviors as not being attacks _per se_ (for instance maybe derailing?), but I think a bigger part of me identifies that the political issue that gives me pause would be covered by "political attacks." On that basis, I'm leaning more towards not adding political beliefs, and instead sticking with the "political attacks" language.

**Comment by mojo-chan** [comment]
The main issue I see is that some political beliefs may conflict with the code, and so it becomes impossible to respect both at the same time. For example, some people believe that trans people cannot really transition, and insist on using the incorrect pronoun or deadnaming them. It's a political belief and can't be reconciled with the rest of the code.

**Comment by mprelude** [comment]
I don't believe the following statements are mutually exclusive:

* You have the right to contribute without being abused or harassed because of your religious or political beliefs.
* A project's development channels are not a place for discussing religious or political beliefs.

We don't expect people to post about their sexuality (although we protect them from abuse based on that), we could coherently do the same for political beliefs & religious beliefs.

**Comment by mojo-chan** [comment]
I broadly agree with you, @mprelude. I'd just say that religious and political beliefs are generally ranked lower than the other things mentioned, in that (as you point out) we would expect people to respect things like gender identity above their own personal beliefs.

We should avoid a situation where people can claim that being "forced" to use a particular pronoun, or merge code from someone whose orientation they find upsetting for religious reasons, is a violation of the code or their rights.

As an example, on another forum someone was complaining that gay people ram their sexuality down his throat, constantly bothering him by discussing what they do in the bedroom. After some investigation it turns out that what he means is that when a gay person casually mentions in normal conversation their same sex partner (e.g. "my wife is an expert in this, try asking her"), to him that was interpreted and being forced to confront their bedroom activity and considered harassment.

This is why the Open Code of Conduct includes the reverse-ism bit. It's controversial, but it is there to deal with people complaining that their intolerance is not being tolerated. It's not just about listing things people shouldn't say or do, it's about protecting people's right to live normal lives without having to hide their protected attributes for fear of getting spurious complaints.

**Comment by mprelude** [comment]
> I broadly agree with you, @mprelude. I'd just say that religious and political beliefs are generally ranked lower than the other things mentioned, in that (as you point out) we would expect people to respect things like gender identity above their own personal beliefs.

Yes, to reiterate, I absolutely don't want to create a scenario where we're protecting political/religious speech to a harmful degree, but rather protecting people from harassment based on their (well known) political/religious beliefs i.e. "you support Donald Trump, you must be an idiot" or "you're a creationist, what do you know about science?" (I think all of us have seen creationist-bashing).

> We should avoid a situation where people can claim that being "forced" to use a particular pronoun, or merge code from someone whose orientation they find upsetting for religious reasons, is a violation of the code or their rights.

+1.

> As an example, on another forum someone was complaining that gay people ram their sexuality down his throat, constantly bothering him by discussing what they do in the bedroom.

This one, as you said, is an investigative task. If someone was going around literally ramming sexuality (of any kind) down others' throats, this would already fall foul of the 'sexual language and imagery' clause.

**Comment by mprelude** [comment]
I am also of the (controversial?) opinion that by extending protection status even to groups which are not typically marginalised, we give those majority groups a vested interest in the CoC and help them to see it as their 'friend' rather than their 'enemy'. Giving everyone a stake in the health of a community can only serve to unite people.

**Comment by mojo-chan** [comment]
Interesting point you make there, about trying to include people. I'm just struggling to see examples where specific protection for religious or political beliefs would not already be covered by things no personal attacks or perhaps something about not dragging politics into technical arguments.

One important difference to consider is that political and religious beliefs are a matter of choice. For example, having a Trump for President email signature or LGBT rainbow flag is a choice and arguably an unwelcome political statement that really shouldn't be brought in to the development of open source projects. On the other hand merely being gay is not a choice, and it is unreasonable to expect people to hide that fact when normal human interaction does sometimes lead to it being implied or revealed (as in the example of the spouse I gave above).

I can see it's a difficult one to call. For example, someone might reasonably want to say "this fix will be delayed because I'm busy at the Tea Party meeting this weekend". It could be argued that is not so different from saying "this fix will be delayed because I'm busy helping my boyfriend move this weekend".

**Comment by mprelude** [comment]
> I'm just struggling to see examples where specific protection for religious or political beliefs would not already be covered by things no personal attacks or perhaps something about not dragging politics into technical arguments.

Could you not say the same for any of those other designated groups, though? A prohibition on insults by definition would prohibit homophobic slurs or anti-Christian slurs, but we list those groups in order to make everyone feel that we welcome diversity.

> For example, someone might reasonably want to say "this fix will be delayed because I'm busy at the Tea Party meeting this weekend". It could be argued that is not so different from saying "this fix will be delayed because I'm busy helping my boyfriend move this weekend".

+1.

> One important difference to consider is that political and religious beliefs are a matter of choice. For example, having a Trump for President email signature or LGBT rainbow flag is a choice and arguably an unwelcome political statement that really shouldn't be brought in to the development of open source projects.

I was thinking more in the instance of knowing peoples' political beliefs or religious beliefs from discussions outside of project spaces, and attacking or dismissing them inside of project spaces because of it. I would tend to agree with you that putting political beliefs in signatures in an OSS space is inflammatory, and I would actually advocate at least a clause in the desired behaviours about avoiding political subjects in project spaces (Go code has some decent wording on this, I think).

**Comment by Gorcenski** [comment]
> protecting people from harassment based on their (well known) political/religious beliefs i.e. "you support Donald Trump, you must be an idiot" or "you're a creationist, what do you know about science?" (I think all of us have seen creationist-bashing).

I think this clearly falls under "political attacks."

**Comment by mojo-chan** [comment]
> Could you not say the same for any of those other designated groups, though? A prohibition on insults by definition would prohibit homophobic slurs or anti-Christian slurs, but we list those groups in order to make everyone feel that we welcome diversity.

I suppose there are two reasons.

1. There is a specific, severe problem in some areas. In an ideal world it shouldn't need to be stated that transphobia is unacceptable and falls under the standard prohibition of not making personal insults, but in practice it seems to be. My spell checker doesn't even recognize the word transphobia.

2. It prevents the reverse-ism issue. No-one can complain that simply failing to hide your orientation or skin colour or whatever is somehow a violation of the CoC, because it says specifically that such claims are themselves against the rules.

You can't tolerate and protect every point of view, because clearly some involve the oppression of others. Unfortunately you can't even state it that way, as some people will claim that others being openly female or black oppresses them (see the recent MRA reaction to The Force Awakens, for example). So you have to pick a side and state it.

**Comment by mprelude** [comment]
> So you have to pick a side and state it.

I'm not good at compromise outcomes, I don't believe that you have to choose between protecting one group and protecting another. Will think more on wording.

I think we got to the right point earlier; that being a protected group does not give you the right to use that status to mount an attack on a member of another group. The fact that someone is trans does not give them the right to harass the Tea Party member, the fact that someone is a Tea Party member does not give them the right to misgender a trans person.

The list of protected groups is not actually a part of the terms and conditions, it's just preamble as I read it, and does not infer any special rights on people because they belong to one of those groups.

**Comment by mprelude** [comment]
> You can't tolerate and protect every point of view, because clearly some involve the oppression of others. 

This is part of my point though, we don't need to tolerate every point of view, we just need to tolerate the people who hold those views. If someone says on their Twitter, "marriage is between a man and a woman", we should tolerate (and not allow harassment of) that person as long as they keep their views off of project spaces.

**Comment by mojo-chan** [comment]
> I think we got to the right point earlier; that being a protected group does not give you the right to use that status to mount an attack on a member of another group. The fact that someone is trans does not give them the right to harass the Tea Party member, the fact that someone is a Tea Party member does not give them the right to misgender a trans person.

I agree fully here, it's just the practical implications... As I said, some people consider others not hiding their nature, or being "forced" to use the "wrong" pronoun to be harassment. At some point you have to say "no, not mis-gendering a trans person is more important than your right to believe they are still male/female and use your preferred pronoun".

> This is part of my point though, we don't need to tolerate every point of view, we just need to tolerate the people who hold those views. If someone says on their Twitter, "marriage is between a man and a woman", we should tolerate (and not allow harassment of) that person as long as they keep their views off of project spaces.

I broadly agree, but again there may be issues. For example, legally a Christian baker might not be allowed to refuse to cater a same-sex wedding on religious grounds, but a same-sex couple's bakery might be able to refuse to bake a cake with the phrase "marriage is between a man and a woman only" on it. I'm not saying that is right or must be reflected here, merely that I'm not sure it's black and white that something said or done outside the project must be ignored.

A recent example would be that Eich guy who was briefly in some C level position at Mozilla. His views made his position untenable because some people refused to work with him or use Mozilla's products as long as he was in that position. Some people said this was a violation of his rights, others said that freedom of speech is not freedom from consequences and you can't realistically expect people to separate what you say or do in your personal life with your professional life.

You can't avoid picking sides, because one way or another you deny someone their right to react in the manner of their choice to something another person does. Again, the key differentiation is between things that are a choice and things which are not.

**Comment by mprelude** [comment]
> I agree fully here, it's just the practical implications... As I said, some people consider others not hiding their nature, or being "forced" to use the "wrong" pronoun to be harassment. At some point you have to say "no, not mis-gendering a trans person is more important than your right to believe they are still male/female and use your preferred pronoun".

Then let's explicitly state this in the expected behaviours section:

* You are expected to respect the expression and identity of other users, for example by using the name and gender pronouns which that person requests.

> A recent example would be that Eich guy who was briefly in some C level position at Mozilla.

The Brendan Eich boycott was counter-productive, though. All it served to achieve was to send a signal to conservatives and even libertarians that their worst fears are right, and that proponents of inclusiveness like you and me are out to exclude them for their "wrongthink". That's what I'm trying to avoid.

> You can't avoid picking sides, because one way or another you deny someone their right to react in the manner of their choice to something another person does. Again, the key differentiation is between things that are a choice and things which are not.

I'd like to lift this negative from the Go code, which I think is a great medium and avoids taking sides:

* Discussing potentially offensive or sensitive issues; this all too often leads to unnecessary conflict.

**Comment by mojo-chan** [comment]
> You are expected to respect the expression and identity of other users, for example by using the name and gender pronouns which that person requests.

I agree with the sentiment but feel that the statement is too specific.

> All it served to achieve was to send a signal to conservatives and even libertarians that their worst fears are right, and that proponents of inclusiveness like you and me are out to exclude them for their "wrongthink".

I see what you mean, but I still think you can't get away from ultimately stating that one thing is acceptable and another is not. Either sexism is not acceptable under any circumstances, or it is acceptable if say you believe that one gender is inferior. You can only accommodate both views if ban people from talking about gender, but that would force everyone to use gender neutral pseudonyms and be extremely careful not to reveal any aspect of their true identity.

While I generally agree that it's best to avoid discussing such issues while developing software, at the same time I don't think people should have to avoid expressing any aspect of their identity that way. Of course, that can include religious or political aspects (I gave examples above, but would add titles such as Reverend or Senator). What I'm saying is that while all of that should be allowed and protected to some extent, when push comes to shove one right has to be maintained over another and any language has to make it clear which one has priority.

Again, the OCC is explicit about this, stating that it will prioritize certain things over others.

**Comment by mprelude** [comment]
I think the difference between our arguments is that I'm talking about personal traits, and not activity.

Let me try to clarify a few examples to see where we both stand on this:

Sarah is a Christian, a political conservative and believes that marriage is a religious institution between one man and one woman.
Sarah tweets about this sometimes on her personal account, but doesn't mention it in the project channels and is cordial with gay members of the community.
Should Sarah be a welcome participant?

Bob is a passionate pro-gay activist who has seen Sarah's tweets. He posts quotes from her tweets to the project space and makes derogatory comments about Sarah's religion and her intelligence.
Should Bob be a welcome participant?

**Comment by mprelude** [comment]
If I were in charge of this community in a BDFL role, I would absolutely welcome Sarah as long as her views on marriage stay outside of the project space, and would absolutely defend her right to participate.

If Sarah and Bob were reversed, and Sarah attacked Bob for his support of gay marriage, I would welcome Bob and defend his right to participate.

**Comment by CoralineAda** [comment]
> On Jan 26, 2016, at 1:11 PM, Matt Prelude <notifications@github.com> wrote:
> 
> I think the difference between our arguments is that I'm talking about personal traits, and not activity.
> 
> Let me try to clarify a few examples to see where we both stand on this:
> 
> Sarah is a Christian, a political conservative and believes that marriage is a religious institution between one man and one woman.
> Sarah tweets about this sometimes on her personal account, but doesn't mention it in the project channels and is cordial with gay members of the community.
> Should Sarah be a welcome participant
> 

Yep
> Bob is a passionate pro-gay activist who has seen Sarah's tweets. He posts quotes from her tweets to the project space and makes derogatory comments about Sarah's religion and her intelligence.
> Should Bob be a welcome participant
> 
> 
Someone should point out that Bob is violating the CoC.

**Comment by mprelude** [comment]
@CoralineAda I'm glad we are on the same page about this. Political inclusiveness matters more than ever with people feeling that we are "out to get them".

**Comment by CoralineAda** [comment]
So to think this through a little more... if someone is socially conservative politically and believes that transgender people are, shall we say, delusional? Is expecting them to respect a transgender participant's pronouns an infringement on their political beliefs?

**Comment by mojo-chan** [comment]
>If I were in charge of this community in a BDFL role, I would absolutely welcome Sarah as long as her views on marriage stay outside of the project space, and would absolutely defend her right to participate.

Right, we would prioritize the rights of gay people over her political beliefs. It would be okay for someone to mention in passing that they have a same-sex partner (see examples I gave above) because that's a normal thing for anyone to do, but bringing up personal political beliefs on the subject is not acceptable.

>if someone is socially conservative politically and believes that transgender people are, shall we say, delusional? Is expecting them to respect a transgender participant's pronouns an infringement on their political beliefs?

Yes, it is, but that's okay. We should prioritize transgender rights over political/religious beliefs.

Personal beliefs are not equal to protected characteristics. If that creates division then it's unfortunate, but unavoidable.

**Comment by mprelude** [comment]
> So to think this through a little more... if someone is socially conservative politically and believes that transgender people are, shall we say, delusional? Is expecting them to respect a transgender participant's pronouns an infringement on their political beliefs?

No, it's an infringement on their freedom of expression, which is fine because a project space is not a free speech venue. It's no different from asking people to refrain from using sexualised language: you may *think* someone else on the project is really hot, but you're not allowed to say it.

**Comment by CoralineAda** [comment]
I decided on not making political beliefs a protected class, but prohibiting political attacks.

**Comment by tripu** [comment]
I think that recent developments (US Elections 2016) have proved that &ldquo;political views&rdquo; are now an excuse for marginalisation and attacks.

The current wording is contradictory: political views are not explicitly protected, but &ldquo;political attacks&rdquo; are condemned?

**Comment by kuro68k** [comment]
Political views are not protected because they are a matter of choice. Political attacks are discouraged because most projects don't want to become a political forum.

The other issue is "tolerance of intolerance". We can't accommodate people who refuse to acknowledge someone's existence or identity because of their political views, because it marginalizes others.

**Comment by tripu** [comment]
@kuro68k:

> Political views are not protected because they are a matter of choice.

So are other protected aspects, like &ldquo;religion&rdquo; and, to some extent, &ldquo;body size&rdquo; and &ldquo;personal appearance&rdquo; (https://github.com/ContributorCovenant/contributor_covenant/issues/73#issuecomment-269289984).

> Political attacks are discouraged because most projects don't want to become a political forum.

It is patronising to explicitly condemn off-topics, and more so to condemn one specific off-topic as if it were particularly poisonous. Team members sometimes shift from technical discussions to off-topic (be it politics, grammar, sports, current world events or anything else), but that does not go against fostering an inclusive and respectful environment. If contributors become distracted with non-relevant topics, someone will eventually call their attention to the issue being discussed (or not).

Soccer (football) is so important to so many people in certain countries. Some teams are more at risk from heated discussions about soccer than from political rows. I am being serious here. Shall we then mention soccer (or sports in general) as a discouraged topic?

> The other issue is "tolerance of intolerance". We can't accommodate people who refuse to acknowledge someone's existence or identity because of their political views, because it marginalizes others.

I'm not sure what that means. But even if I take it quite literally, I don't see the danger. *&ldquo;Contributor X identifies as a socialist, but judging by his views on subject Y, and considering that socialism proclaims Z, I am convinced he's actually a conservative&rdquo;.* There you have it, someone negating someone else's &ldquo;identity&rdquo;. It may be wrong, it may be distracting, it may be irrelevant to everybody around. But I don't see the need to forbid or discourage an expression like that.

**Comment by kuro68k** [comment]
> So are other protected aspects, like “religion” and, to some extent, “body size” and “personal appearance” 

Religion should be removed. It is a choice, and it is sometimes incompatible with being respectful and tolerant of other's non-choices like gender and sexuality.

Body size and personal appearance are not choices. If they were everyone would like like a magazine model. Also, they don't cause any conflict with tolerating others.

As for political positions and various other off-topic issues, the problem is that it then puts the onus on the people who is being affected by the discussion to complain. Often that leads to cries of "political correctness" and "SJW" and other silencing tactics. So it's better to just avoid discussing well known controversial topics.

Bringing up football sounds like reductio ad absurdum.

> “Contributor X identifies as a socialist, but judging by his views on subject Y, and considering that socialism proclaims Z, I am convinced he's actually a conservative”. There you have it: someone negating someone else's “identity”. A “political attack”. It may be wrong, it may be distracting, it may be irrelevant to everybody around. But I don't see the need to forbid or discourage an expression like that.

It's irrelevant flamebait, and the only possible reasons to bring it up are to start an argument or to discourage that person from contributing by forcing them to defend their political position.

**Comment by tripu** [comment]
I disagree again with you on a few points, @kuro68k. I think I won't go into details, as I suspect you reflect the ideas of the majority of contributors to this project better than I do. I don't think I'll change anybody's mind. I appreciate your answers.

Perhaps, the fact that we strongly disagree about some &ldquo;basic&rdquo; concepts (what is tolerable, what constitutes harassment, what areas are safe) shows the impossibility of this covenant itself: it is so difficult to define what is &ldquo;an open and welcoming environment&rdquo; in terms that everybody will agree on.

**Comment by tripu** [comment]
@kuro68k, I wrote a bit on my scepticism about these codes of conduct here: https://github.com/gnab/remark/pull/398#issuecomment-269339964.

Thank you for your interest in understanding dissenting opinions like mine :)

**Comment by Aspie96** [comment]
> > On Jan 26, 2016, at 1:11 PM, Matt Prelude [notifications@github.com](mailto:notifications@github.com) wrote:
> > I think the difference between our arguments is that I'm talking about personal traits, and not activity.
> > Let me try to clarify a few examples to see where we both stand on this:
> > Sarah is a Christian, a political conservative and believes that marriage is a religious institution between one man and one woman.
> > Sarah tweets about this sometimes on her personal account, but doesn't mention it in the project channels and is cordial with gay members of the community.
> > Should Sarah be a welcome participant
> 
> Yep

OpalGate.

**Pull request closed without merging**
