### PR TITLE
Added a new project detail

### PR DESCRIPTION
**Pull request by riddhisharma2000**

### CODE REVIEW

**Comment by dbalde** [comment]
Bonjour le monde

**Review by CoralineAda — COMMENTED** [review]
Can you please resolve the merge conflict?

**Comment by mbtools** [comment]
- Visual F# is already listed as .NET
- voice-web repo does not include CODE_OF_CONDUCT.md

Suggest closing

**Comment by CoralineAda** [comment]
Resolved in #1069

**Pull request closed without merging**
