### PR TITLE
NOT_SPELLED_CORRECTLY_&_IT'S MEANING

### PR DESCRIPTION
**Pull request by Devashishsingh98**
The word इलेक्ट्रॉनिक is not correct for translation, it is direct spelling of the word from English to Hindi. The true meaning of "Electronic" cannot be understood.The exact translation for "Electronic"  is "विद्युतीय-" with a dash on it's side, which shows merging of this two words.And same goes for the word "पोस्टिंग".

### CODE REVIEW

**Comment by Devashishsingh98** [comment]
Hello,everyone. I am new here,please tell me if something is wrong.

**Comment by CoralineAda** [comment]
Thank you for the correction!

**Comment by Devashishsingh98** [comment]
sir/madam,

1. Does it counted as contribution in Hactoberfest ?

**Comment by CoralineAda** [comment]
Yes it does. Congrats! :)

**Pull request merged**
