### PR TITLE
faq: Listing protected classes is not an invitation to discriminate for other reasons

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by joshtriplett** [comment]
(Note that I added the parenthetical at the end of this entry to ensure that people don't use it as an excuse, for the same reason "political affiliation" is intentionally not listed as a protected class.)

**Comment by CoralineAda** [comment]
Thanks Josh, this is great!

**Comment by lordpidey** [comment]
This seems like a bad idea.  Instead of placing clarification in an area outside of the code of conduct, let's make the code of conduct stand on it's own legs.

**Comment by joshtriplett** [comment]
@lordpidey I don't feel that these clarifications say things that *aren't* true of the document itself; rather, they're explaining things that might require additional background or shared context.

Also, precedent: https://www.gnu.org/licenses/gpl-faq.html

**Pull request merged**
