### PR TITLE
Update adopters.csv

### PR DESCRIPTION
**Pull request by meikalei**
- converted code of conduct to rst file

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hi, I clicked through to the codes of conduct files and it looks like you didn't put the contact method in place for how violations should be reported. Was this an oversight?

**Comment by meikalei** [comment]
> Hi, I clicked through to the codes of conduct files and it looks like you didn't put the contact method in place for how violations should be reported. Was this an oversight?

Hi! we'll be updating the contact once we have finalized it, for the meantime, violations can be reported to the repo admins

**Comment by CoralineAda** [comment]
> Hi! we'll be updating the contact once we have finalized it, for the meantime, violations can be reported to the repo admins
> 

How would they know how to contact the repo admins?

**Comment by meikalei** [comment]
Hi @CoralineAda ,
We have updated the contact method

**Review by CoralineAda — APPROVED** [review]
Thanks so much!

**Pull request merged**
