### PR TITLE
Added Rocket.Chat

### PR DESCRIPTION
**Pull request by engelgabriel**

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in that repo. Am I missing something?

**Comment by engelgabriel** [comment]
Sorry, do I have to copy the file?
I was referencing at https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/1.%20Contributing

**Comment by CoralineAda** [comment]
That’s okay, but it’s really hard to find so many people will assume that you do not have one. The preferred method is to add CODE_OF_CONDUCT.md to your project’s root directory. (You can then reference it from the Contributing document.)

**Comment by engelgabriel** [comment]
Is this ok? 
https://github.com/RocketChat/Rocket.Chat/commit/3d977131a30b6546dfc4ce11154d6a5b47baa4a4

**Comment by CoralineAda** [comment]
Perfect! Thanks.

**Pull request merged**
