### PR TITLE
Minor fixes to Turkish translation

### PR DESCRIPTION
**Pull request by wfdd**
@ugurcan377: if you could please take a look.

### CODE REVIEW

**Comment by ugurcan377** [comment]
Just noticed few of the errors and i was about send another pr. 
They're great thanks for fixes.

**Comment by wfdd** [comment]
Thanks for taking a look.

**Comment by wfdd** [comment]
@CoralineAda: I think we can merge this now. :)

**Comment by CoralineAda** [comment]
Thanks!

**Pull request merged**
