### PR TITLE
Added Linkrot Project

### PR DESCRIPTION
**Pull request by marshalmiller**
This is one of my projects that utilizes your code of conduct for contributions.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I don't see a code of conduct in that repository?

**Comment by marshalmiller** [comment]
I'm sorry. It is a section of the CONTRIBUTING Guidelines at https://github.com/marshalmiller/linkrot/blob/main/CONTRIBUTING.md. 
I saw this done with kubertenes and GitLab. If that is against the rules, I'll add a separate code of conduct to the root folder. I just felt like it belonged in the contributing section.

**Comment by CoralineAda** [comment]
It's good to surface it in your README and CONTRIBUTING docs, but standard practice is to have a distinct CODE_OF_CONDUCT.md in your repo's root directory.

**Comment by marshalmiller** [comment]
I have added it to the root folder.

**Review by CoralineAda — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
